name: OpenWrt-CI
on:
  push:
    branches:
      - master
  watch:
    types: started
env:
  SDK_URL: https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
  SDK_NAME: openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64
  package_URL: https://github.com/mchome/openwrt-dogcom.git
jobs:

  Make:
    name: make through SDK
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: 拉取SDK
        run: |
          wget -c $SDK_URL
      - name: 解压
        run: |
          tar xvf *.tar.xz
